name: 'Planetscale Create Deploy Request'
description: 'Greet someone and record the time'
inputs:
  org:
    description: planetscale org name
    required: true
  database:
    description: planetscale database to use
    required: true
  branch:
    description: planetscale database branch to run deploy request on
    required: true

outputs:
  DEPLOY_REQUEST_NUMBER: # id of output
    description: 'The planetscale deploy request number'
  DEPLOY_REQUEST_URL:
    description: 'The planetscale deploy request URL for link'
  BRANCH_DIFF:
    description: 'The SQL file diff text for the deploy request'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.org }}
    - ${{ inputs.database }}
    - ${{ inputs.branch }} 
